### ISSUE TITLE
DFV-Artifact Installation Error: ERROR: Could not find a version that satisfies the requirement tensorflow<2.0,>=1.15 

### ISSUE THREAD

**Issue by shenw000** [less-lab-uva/DFV-Artifact#1]
Hi, I am installing DFV-Artifact on UBUNTU 20.04, Python 3.7 using the ./install.sh command. But encountered the following error, and can anyone help?

Requirement already satisfied: setuptools in /home/shenw/workspace/anaconda3/lib/python3.8/site-packages (62.1.0)
Collecting dnnf==0.0.4
  Using cached dnnf-0.0.4-py3-none-any.whl (21 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow<2.0,>=1.15 (from dnnf) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.9.0rc0)
ERROR: No matching distribution found for tensorflow<2.0,>=1.15
Requirement already satisfied: cleverhans==3.0.1 in /home/shenw/workspace/anaconda3/lib/python3.8/site-packages (3.0.1)
Requirement already satisfied: nose in /home/shenw/workspace/anaconda3/lib/python3.8/site-packages (from cleverhans==3.0.1) (1.3.7)

It seems that no tensorflow version matches your requirement for DNNF. I wonder if it due to my cuda version 11.4? It looks like that your required tensorflow version is >=1.15 and <2.0, and does it mean the cuda version has to be something less than cuda 11.4?

Best regards,

**Comment by dlshriver** [comment]
It looks like you are using python3.8 instead of python3.7 (as shown in the line `Requirement already satisfied: setuptools in /home/shenw/workspace/anaconda3/lib/python3.8/site-packages (62.1.0)`). Unfortunately, this artifact only supports up to python3.7 since that is the latest version of python supported by the version of tensorflow required by some of our dependencies. Switching to python3.7 should hopefully fix the issue.

**Comment by shenw000** [comment]
Thanks! I am now using a Python 3.7 conda environment to run the command ./install.sh. I found two errors:

1:
Installing collected packages: flatbuffers, numpy, onnxruntime
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.5
    Uninstalling numpy-1.18.5:
      Successfully uninstalled numpy-1.18.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.2.3 requires numpy<1.19.0,>=1.16.0, but you have numpy 1.21.6 which is incompatible.
dnnv 0.4.4 requires numpy<1.20,>=1.18, but you have numpy 1.21.6 which is incompatible.

2. 
Collecting cloudpickle>=1.3
  Using cached cloudpickle-2.0.0-py3-none-any.whl (25 kB)
Requirement already satisfied: typing-extensions in ./.venv/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->cleverhans==3.0.1) (4.1.1)
Installing collected packages: nose, dm-tree, python-dateutil, pycodestyle, mnist, kiwisolver, gast, fonttools, decorator, cycler, cloudpickle, tensorflow-probability, matplotlib, cleverhans
  Attempting uninstall: gast
    Found existing installation: gast 0.2.2
    Uninstalling gast-0.2.2:
      Successfully uninstalled gast-0.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 1.15.5 requires gast==0.2.2, but you have gast 0.5.3 which is incompatible.
Successfully installed cleverhans-3.0.1 cloudpickle-2.0.0 cycler-0.11.0 decorator-5.1.1 dm-tree-0.1.7 fonttools-4.32.0 gast-0.5.3 kiwisolver-1.4.2 matplotlib-3.5.1 mnist-0.2.2 nose-1.3.7 pycodestyle-2.8.0 python-dateutil-2.8.2 tensorflow-probability-0.16.0

**Comment by shenw000** [comment]
For Error 1, upon further investigation, I found that onnxruntime requires numpy 1.21.0, while
tensorflow 2.2.3 requires numpy<1.19.0,>=1.16.0, 
dnnv 0.4.4 requires numpy<1.20,>=1.18
So if I choose numpy 1.18.5 for install (meeting requirements for tensorflow 2.2.3 and dnnv 0.4.4) it will violate the requirements of onnxruntime.
Is there any way we can use an earlier version of onnxruntime that uses numpy 1.18.5 instead of 1.21.0?

**Comment by dlshriver** [comment]
Have you tried running any of the artifacts? Those errors from pip are just warnings, it still successfully installed dependencies. The dependencies as installed should work correctly without compatibility issues.

**Comment by shenw000** [comment]
Thanks! You're right. The artifacts in RQ1 still run.

**Comment by dlshriver** [comment]
Great! I've added a warning to INSTALL.md to clarify that these error messages are expected and should not affect execution of the studies.
