### ISSUE TITLE
Errors when running verifier neurify in RQ1

### ISSUE THREAD

**Issue by shenw000** [less-lab-uva/DFV-Artifact#2]
Hi, I am running the verifier neurify in RQ1 in foreground. It seems to complete normally in about 5 days. When I take a look at the results in the following folder output/Verifiers/Neurify/run1/property1/resultsDNN/dnnv_output/, I found that these results_propertyx.txt files have various sizes, which can be categorized into two groups: large (>2KB) or small (<1KB).

-rw-rw-r-- 1 shenw shenw 2214 Apr 15 23:29 results_property0.txt
-rw-rw-r-- 1 shenw shenw  690 Apr 15 23:29 results_property1.txt
-rw-rw-r-- 1 shenw shenw 2106 Apr 16 00:29 results_property2.txt
-rw-rw-r-- 1 shenw shenw 2366 Apr 16 01:29 results_property3.txt
-rw-rw-r-- 1 shenw shenw 2366 Apr 16 02:29 results_property4.txt
-rw-rw-r-- 1 shenw shenw  690 Apr 16 02:29 results_property5.txt
-rw-rw-r-- 1 shenw shenw 2366 Apr 16 03:29 results_property6.txt
-rw-rw-r-- 1 shenw shenw 2366 Apr 16 04:29 results_property7.txt
-rw-rw-r-- 1 shenw shenw 2366 Apr 16 05:29 results_property8.txt
-rw-rw-r-- 1 shenw shenw  757 Apr 16 06:10 results_property9.txt

Upon further examination, it is observed that the large sized results_property files contain error messages, while small sized results_property files contain the correct results. For example, results_property0.txt contains the following:

=========================================================
Verifying property:
Forall(x0, (((numpy.argmax(N(x0)) == 7) & (x0 <= 1) & (0 <= x0)) ==> (abs((N(x0)[(0, 7)] - N(x0)[(0, 6)])) > abs((N(x0)[(0, 7)] - N(x0)[(0, 5)])))))

Verifying Networks:
N:
Input_0                         : Input([ -1 784], dtype=float32)
Gemm_0                          : Gemm(Input_0, ndarray(shape=(24, 784)), ndarray(shape=(24,)))
Relu_0                          : Relu(Gemm_0)
Gemm_1                          : Gemm(Relu_0, ndarray(shape=(24, 24)), ndarray(shape=(24,)))
Relu_1                          : Relu(Gemm_1)
Gemm_2                          : Gemm(Relu_1, ndarray(shape=(10, 24)), ndarray(shape=(10,)))

Traceback (most recent call last):
  File "/home/shenw/workspace/sandbox/nn_assurance/DFV-Artifact/DNNV/dnnv/verifiers/common/base.py", line 110, in run
    subproperty_result, cex = self.check(subproperty)
  File "/home/shenw/workspace/sandbox/nn_assurance/DFV-Artifact/DNNV/dnnv/verifiers/common/base.py", line 86, in check
    *executor_inputs, verifier_error=self.verifier_error
  File "/home/shenw/workspace/sandbox/nn_assurance/DFV-Artifact/DNNV/dnnv/verifiers/common/executors/commandline.py", line 34, in run
    ready, _, _ = select.select([stream], [], [], 0)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shenw/workspace/sandbox/nn_assurance/DFV-Artifact/DNNV/.venv/bin/dnnv", line 8, in <module>
    sys.exit(_main())
  File "/home/shenw/workspace/sandbox/nn_assurance/DFV-Artifact/DNNV/dnnv/__main__.py", line 80, in _main
    return exit(main(*cli.parse_args()))
  File "/home/shenw/workspace/sandbox/nn_assurance/DFV-Artifact/DNNV/dnnv/__main__.py", line 58, in main
    result, cex = verifier.verify(phi, **params)
  File "/home/shenw/workspace/sandbox/nn_assurance/DFV-Artifact/DNNV/dnnv/verifiers/common/base.py", line 80, in verify
    return cls(phi, **kwargs).run()
  File "/home/shenw/workspace/sandbox/nn_assurance/DFV-Artifact/DNNV/dnnv/verifiers/common/base.py", line 116, in run
    return result, cex
  File "/home/shenw/workspace/anaconda3/envs/dfv/lib/python3.7/tempfile.py", line 806, in __exit__
    def __exit__(self, exc, value, tb):
KeyboardInterrupt
=========================================================

Other "large" results_property files have similar error message. This is little surprising to me as I didn't hit the keyboard to interrupt the execution of verify.sh. I did start new terminal for doing other tasks. Could you help me to resolve this issue?

I also attached the zip of the complete folder of rq1/output/Neurify/ below.

Thanks,
shenw000

 
[output.zip](https://github.com/less-lab-uva/DFV-Artifact/files/8631930/output.zip)

**Comment by dlshriver** [comment]
This is expected. Our scripts send a SIGINT signal to DNNV processes on timeout. The later processing scripts deal with this appropriately.

**Comment by shenw000** [comment]
Understood. Yes, the timeout set to 3600 seconds in dnnv_pipeline.py.  Have you ever reached the longest running time for a property verification without setting the timeout? Looks like more than half of the property verifications reached timeout point.

**Comment by dlshriver** [comment]
Many will hit the timeout. Verification can take a *very* long time. We did not let all of the verification jobs run to completion because they could take many days to finish, so we set a limit of 1 hour.
