### ISSUE TITLE
Errors when running verifier Verinet in RQ1

### ISSUE THREAD

**Issue by shenw000** [less-lab-uva/DFV-Artifact#3]
Hi, 

I am running verifier Verinet in RQ1, which seems to terminate normally. However, when I examined its results, it shows such error in file, e.g. DFV-Artifact/rq1/output/Verifiers/Verinet/run0/property1/results/dnnv_output/results_property0.txt:

Verifying property:
Forall(x0, (((-3 <= x0) & (numpy.argmax(N(x0)) == 7) & (x0 <= 3)) ==> (abs((N(x0)[(0, 7)] - N(x0)[(0, 6)])) > abs((N(x0)[(0, 7)] - N(x0)[(0, 5)])))))

Verifying Networks:
N:
Input_0                         : Input([-1  2], dtype=float32)
Gemm_0                          : Gemm(Input_0, ndarray(shape=(24, 2)), ndarray(shape=(24,)))
Relu_0                          : Relu(Gemm_0)
Gemm_1                          : Gemm(Relu_0, ndarray(shape=(24, 784)), ndarray(shape=(784,)))
Relu_1                          : Relu(Gemm_1)
Gemm_2                          : Gemm(Relu_1, ndarray(shape=(784, 784)), ndarray(shape=(784,)))
Relu_2                          : Relu(Gemm_2)
Gemm_3                          : Gemm(Relu_2, ndarray(shape=(784, 24)), ndarray(shape=(24,)))
Relu_3                          : Relu(Gemm_3)
Gemm_4                          : Gemm(Relu_3, ndarray(shape=(24, 24)), ndarray(shape=(24,)))
Relu_4                          : Relu(Gemm_4)
Gemm_5                          : Gemm(Relu_4, ndarray(shape=(10, 24)), ndarray(shape=(10,)))

dnnv.verifiers.verinet
  result: VerinetError(Return code: 1)
  time: 1.2872

Please advise. What might went wrong in this run.

Thanks in advance,
shenw000

**Comment by dlshriver** [comment]
VeriNet requires gurobi. Make sure you have a valid gurobi license installed, otherwise it will not be able to run. For more details see [INSTALL.md](https://github.com/less-lab-uva/DFV-Artifact/blob/main/INSTALL.md).
