### ISSUE TITLE
Understanding result_summary.md

### ISSUE THREAD

**Issue by shenw000** [less-lab-uva/DFV-Artifact#4]
When I ran the Neurify in RQ1,  it produces a result_summary.md for each run.
For example, in one of the result_summary.md, the result of validation of property 9 is below.
=============================================================
#Property 9
##Status: sat
###Time: 65.1274
![](./images/image9.png)
###DNN Prediction: 
T_shirt/top :-4.3968973
Trouser :-2.3682013
Pullover :-5.971979
<mark>Dress :-2.3681993</mark>
Coat :-4.3742757
Sandal :-4.175142
Shirt :-3.1441832
Sneaker :-2.3682
Bag :-5.1286554
Ankle boot :-2.641714
===========================================================

What is the number after each class name? More specifically, what does Trouser :-2.3682013 mean? 

Thanks for your help in advance!

**Comment by Felipetoledo4815** [comment]
Hi,

Those numbers are the output values of the network for each class. For the case of the Trouser, -2.3682013 is the output value for that class.
